version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DocumentConverterStack"
s3_prefix = "DocumentConverterStack"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DomainName=\"\""
image_repositories = []
